CREATE DATABASE FinalDB;
GO

USE FinalDB;

CREATE TABLE Platforms(
PlatformID INT PRIMARY KEY IDENTITY,
PlatformName VARCHAR(50) NOT NULL,
PlatformManufacturer VARCHAR(50) NULL,
);
GO
CREATE TABLE Genres(
GenreID INT PRIMARY KEY IDENTITY,
GenreName VARCHAR(50) NOT NULL,
);
GO
CREATE TABLE Developers(
DeveloperID INT PRIMARY KEY IDENTITY,
DeveloperName VARCHAR(50) NOT NULL,
CountryBased VARCHAR(50) NULL,
);
GO
CREATE TABLE Ratings(
RatingID INT PRIMARY KEY IDENTITY,
RatingName VARCHAR(50) NOT NULL,
);
GO
CREATE TABLE Games(
GameID INT PRIMARY KEY IDENTITY,
GameName VARCHAR(100) NOT NULL,
ReleaseDate DATE NULL,
DeveloperID INT NULL,
RatingID INT NULL
);
GO
ALTER TABLE Games WITH CHECK
ADD CONSTRAINT FK_Developer_Games FOREIGN KEY(DeveloperID) REFERENCES Developers (DeveloperID)
ON UPDATE CASCADE;
GO
ALTER TABLE Games WITH CHECK
ADD CONSTRAINT FK_Rating_Games FOREIGN KEY(RatingID) REFERENCES Ratings (RatingID)
ON UPDATE CASCADE;
GO
CREATE INDEX idx_DeveloperID_Games ON Games(DeveloperID);
CREATE INDEX idx_RatingID_Games ON Games(RatingID);
GO
CREATE TABLE GamePlatform(
GameID INT NOT NULL,
PlatformID INT NOT NULL,
PRIMARY KEY (GameID, PlatformID)
);
GO
ALTER TABLE GamePlatform WITH CHECK
ADD CONSTRAINT FK_Game_GamePlatform FOREIGN KEY(GameID) REFERENCES Games (GameID)
ON UPDATE CASCADE;
GO
ALTER TABLE GamePlatform WITH CHECK
ADD CONSTRAINT FK_Platform_GamePlatform FOREIGN KEY(PlatformID) REFERENCES Platforms (PlatformID)
ON UPDATE CASCADE;
GO
CREATE TABLE GameGenre(
GameID INT NOT NULL,
GenreID INT NOT NULL,
PRIMARY KEY (GameID, GenreID)
);
GO
ALTER TABLE GameGenre WITH CHECK
ADD CONSTRAINT FK_Game_GameGenre FOREIGN KEY(GameID) REFERENCES Games (GameID)
ON UPDATE CASCADE;
GO
ALTER TABLE GameGenre WITH CHECK
ADD CONSTRAINT FK_Genre_GameGenre FOREIGN KEY(GenreID) REFERENCES Genres (GenreID)
ON UPDATE CASCADE;
GO